//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkJack.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusMsg
    {
        public OrderStatusMsg()
        {
            this.OrderStatus = new HashSet<OrderStatu>();
        }
    
        public string message { get; set; }
        public int id { get; set; }
    
        public virtual ICollection<OrderStatu> OrderStatus { get; set; }
    }
}
