//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkJack.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public int id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> statusId { get; set; }
        public string place { get; set; }
    
        public virtual OrderHeader OrderHeader { get; set; }
        public virtual OrderStatusMsg OrderStatusMsg { get; set; }
    }
}
