//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkJack.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id { get; set; }
        public Nullable<int> orderId { get; set; }
        public string paymentType { get; set; }
        public Nullable<bool> isSuccess { get; set; }
        public string error { get; set; }
    
        public virtual OrderHeader OrderHeader { get; set; }
    }
}
