//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkJack.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Inventories = new HashSet<Inventory>();
            this.Wishlists = new HashSet<Wishlist>();
            this.Images = new HashSet<Image>();
        }
    
        public string productId { get; set; }
        public string productName { get; set; }
        public string description { get; set; }
        public Nullable<double> price { get; set; }
        public string categoryId { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.DateTime> infoRegDate { get; set; }
        public Nullable<double> discount { get; set; }
        public string offerText { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<Wishlist> Wishlists { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
