//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkJack.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificationMsg
    {
        public VerificationMsg()
        {
            this.UserDocuments = new HashSet<UserDocument>();
        }
    
        public int id { get; set; }
        public string msg { get; set; }
    
        public virtual ICollection<UserDocument> UserDocuments { get; set; }
    }
}
